script:
- echo "TBranch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
- export TARGET_APP = APP_BRANCH
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then export TARGET_APP = APP_MASTER;fi
- echo "TARGET_APP is ($TARGET_APP) "